Revert "overlay: mcom03fc: extlinux: Mount root as ext2 ro"
This reverts commit d8184b2a95ead4135d9d888cb7c83257a17ada82.

Reason for revert:

The following error is occurred when tar2dev is used:

error: couldn't mount because of unsupported optional features (2c0)

Change-Id: I0d8110271b5fc0ba2b49eac282f02167f54dab38