Revert "overlay: common: extlinux: Mount root as ext2 rw"
This reverts commit eb84293f8fe5c596307621c04bd6e1c77f4a299c.

Reason for revert:

The following error is occurred when tar2dev is used:

error: couldn't mount because of unsupported optional features (2c0)

Change-Id: I8fbaaa80d1569930a6e0eea2d55dd33e26624aca